#include<stdio.h>
#include<string.h>
#include<conio.h>
int main()
{
	char m[23],Qw[23];
	printf("enter the passord");
	gets(m);
	if(strcmp(m,"<^>")==0)
	{char a[23],b[23];
	printf("enter your half name ");
	gets(a);
	printf("enter your remaing name");
	gets(b);
	strcat(a,b);
	printf("WELCOME %s TO CALCULATOR APP!!!\n\n\n",strupr(a));
	
	int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	else
	{
		printf("thank you for dowloading the app click any key to continue");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	else
	{
		printf("thank you for dowloading the app click any key to continue");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	else
	{
		printf("thank you for dowloading the app click any key to continue");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	else
	{
		printf("thank you for dowloading the app click any key to continue");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	else
	{
		printf("thank you for dowloading the app click any key to continue");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	else
	{
		printf("thank you for dowloading the app click any key to continue");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	else
	{
		printf("thank you for dowloading the app click any key to continue");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	else
	{
		printf("thank you for dowloading the app click any key to continue");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
		scanf("%s",&Qw);
	if(strcmp(Qw,"y")==0){
			int A,B,C,D,E,F,G,H,L,M,N,O,Q,R,S,T,W,X,Y;
	printf("=> PLEASE ENTER THE NUMBER 1\n");
	scanf("%d",&A);
	printf("=> PLEASE ENTER THE NUMBER 2\n");
	scanf("%d",&B);
	C = A+B;
	printf("the addition is %d\n",C);
	C= A-B;
	printf("the subraction is %d\n",C);
	C= A*B;
	printf("the multiplication is %d\n",C);
	C = A/B;
	printf("the division is %d\n",C);
	C = A%B;
	printf("the module is %d\n",C);
	C = A++;
	printf("the increment of your  first number is%d\n",C);
	C = A--;
	printf("the decrement of your first number is %d\n",C);
	C = B++;
	printf("the increment of your second number is %d\n",C);
	C = B--;
	printf("the decrement of your second number is %d\n",C);
	C = A+A;
	printf("the addition of %d+%d=%d\n",A,A,A+A,C);
	C = B+B;
	printf("the addition of %d+%d=%d\n ",B,B,B+B,C);
	C = A*A;
	printf("the multiplication of %d*%d=%d\n",A,A,A*A,C);
	C = B*B;
	printf("the multiplication of %d*%d=%d\n",B,B,B*B,C);
	C =(A+B)*(A+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)*(A-B);
	printf("the solution of (%d-%d)*(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)*(A+A);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)*(B+B);
	printf("the solution of (%d+%d)*(%d+%d) = %d\n",B,B,B,B,C);
	C = A/A;
	printf("the divison of %d/%d=%d\n",A,A,A/A,C);
	C = B/B;
	printf("the divison  of %d/%d=%d\n",B,B,B/B,C);
	C =(A+B)/(A+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,B,A,B,C);
	C = (A-B)/(A-B);
	printf("the solution of (%d-%d)/(%d-%d) = %d\n",A,B,A,B,C);
	C = (A+A)/(A+A);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",A,A,A,A,C);
	C = (B+B)/(B+B);
	printf("the solution of (%d+%d)/(%d+%d) = %d\n",B,B,B,B,C);
	printf("PUBLISHERS:<^>SRIPTED\nDEVELOPED BY:R.RAGUL RAJ\nDEVELOPED DATE:9.9.2023\nVERSION:2\n");
	printf("if you want to continue the app (y/n)");
	}
	else
	{
		printf("thank you for dowloading the app click any key to continue");
	}
	return 0;
}
}